package org.drools.chance
 

import java.io.FileWriter;


declare Message
	status : int
end

global FileWriter writer;

rule "TestOpDegs"	

	kind "Lukas"

	when
		
		
		(
		Message( status == 0 && @( kind="Lukas" ) (status random 1 && @( kind="Prod" ) status random -1)) @( kind="Min" prior="0.04444")
		or @( kind="Lukas" )
		Message(status not ~random 2)
		)
		
		
		not (Message(status ~random 3)
			and @( kind="Lukas" )
			Message(status ~random 4)
			)
				
				
		exists Message(s : status ~random 5 , status ~random 6) //@( kind="Lukas" prior="0.99321")
		
		((equiv
			Message( s1 : status ~random 8)
			Message( s2 : status ~random 9)
		))
									
	then
	
		System.out.println("Degrees test " + drools.getEvaluation().expand());		
		
		writer.write("Degrees test " + drools.getEvaluation().expand());
		
		System.out.println("Final output " + drools.getConsequenceDegree());
end


