package org.drools.chance;

import java.io.FileWriter;

declare Message
	status : int @key
	message : String
end

global FileWriter writer;

	
rule "Test Exist 4"	
	when
		exists (
				   Message( status == 0 )
				   and 
				   Message( status == 1)							
		)
	then
		
		writer.write("Existential check "+drools.getConsequenceDegree()+"\n"+drools.getEvaluation().expand()+"\n\n");
		System.out.println("Existential check "+drools.getConsequenceDegree());			
end
