package org.drools.chance;

import java.io.FileWriter;

declare Message
	status : int @key
	message : String
end

global FileWriter writer;

//Test simple forall using exist
rule "Test Exist 6"	
	when
		not ( 
			exists (
				   	not ( Message( status ~random )
				   							
		) ) )
	then
		
		writer.write("Existential check "+drools.getConsequenceDegree()+"\n"+drools.getEvaluation().expand()+"\n\n");
		System.out.println("Existential check "+drools.getConsequenceDegree());
			
end
