package org.drools.chance;

import java.io.FileWriter;

declare Message
	status : int @key
	message : String
end

global FileWriter writer;

// Test external variable binding
rule "Test Exist 5"	
	when
		$m : Message($s : status == 0)
		exists ( Message(status > $s) )
	then
		writer.write("\n\n Conditional join with existence\n");
		writer.write("\t Rule triggered for " + $m.getMessage() + "\n");
		
		writer.write("Existential check "+drools.getConsequenceDegree()+"\n"+drools.getEvaluation().expand()+"\n\n");
		System.out.println("Existential check "+drools.getConsequenceDegree());
			
end
