package org.drools.chance;

import java.io.FileWriter;

declare Message
	status : int @key
	message : String
end

global FileWriter writer;


//True when Msg=1 appears, becomes false on insertion of Msg=2
rule "Test Forall 2"	
	when
		Message( status == @(cut="true") 1)
		forall (
					m : Message()
					Message( this == m, status <= 1)
					Message( this == @(cut="true") m, status > -1)					
		)
	then
		
		writer.write("Existential check "+drools.getConsequenceDegree()+"\n"+drools.getEvaluation().expand()+"\n\n");
		System.out.println("Existential check "+drools.getConsequenceDegree());
			
end