package org.drools.chance;

import java.io.FileWriter;

declare Message
	status : int @key
	message : String
end

global FileWriter writer;


rule "Test Join 2"	
	when
		
					m : Message( status == 1)
					and			
					p : Message( this == @(cut = "true") m, status == 1)						
		
	then
		writer.write(m.getMessage() + "  " + p.getMessage());
		writer.write("Self-Join check "+drools.getConsequenceDegree()+"\n"+drools.getEvaluation().expand()+"\n\n");
		System.out.println("Existential check "+drools.getConsequenceDegree());
		System.out.println(m.getMessage() + "  " + p.getMessage());	
end
