package org.drools.chance;

import java.io.FileWriter;

declare Message
	status : int @key
	message : String
end

global FileWriter writer;


rule "Test Join 2"	
	when
		
					m : Message()								
					p : Message( this == @(cut="true") m, $s : status > -1)
				 	q : Message( status == $s)						
		
	then
		writer.write(m.getMessage() + "  " + p.getMessage() + q.getMessage() + "\n");
		writer.write("Self-Join check "+drools.getConsequenceDegree()+"\n"+drools.getEvaluation().expand()+"\n\n");
		System.out.println("Existential check "+drools.getConsequenceDegree());
		System.out.println(m.getMessage() + "  " + p.getMessage());	
end
