package org.drools.chance;
 

import java.io.FileWriter;


declare Message
	status : int @key
	message : String
end


global FileWriter writer;



rule "Test"

	when	
		(
			$msg : Message( $stat: status == 0 && status == 1 )
			or 
			(	
				Message(status ~random && (message random || status random))
				and
				Message(status ~random )
			)
		)
		
		
		not (Message(status ~random )
			and
			Message(status ~random )
			)
				
		Message( $sjust : status )
		
		Message( status > $stat )
		
		Message( status == status , status > $msg.status )
		
		
	then
		System.out.println();
end