package org.drools.test;

import java.util.List;
import org.drools.Cheese;


global java.util.List list

function void addToTheList( List list, Object element ) {
    list.add( element );
}

function void addFive(List list) {
	addToTheList( list, new Integer(5) );
}

rule "global rule test"
    when
        Cheese( )
    then
		addFive( list );
		// Calling methods does not mess with function calls
		System.out.println(list);
end    