package org.drools.examples.chance
 
import org.drools.examples.chance.Room;
import org.drools.examples.chance.Fan;
import java.io.FileWriter;


global FileWriter writer;




rule "Cold"
	when 
		$r : Room( temperature cold[] 0)		
	then
		drools.inject(new Fan(),"org.drools.examples.chance.Fan.speed","seems","stop");	              
end

rule "Warm"
	when
		$r : Room( temperature cool[] 0)
	then
		drools.inject(new Fan(),"org.drools.examples.chance.Fan.speed","seems","stop");
end

rule "Hot"
	when
		$r : Room( temperature hot[] 0)
	then
		drools.inject(new Fan(),"org.drools.examples.chance.Fan.speed","seems","fast");
end





rule "Fan1" 
	when 
		$f : Fan( speed seems[] "fast")
	then
		$f.setSpeed("fast",drools.getConsequenceDegree());
		writer.write("\n\n ********** Set speed to fast ****** \n\n" + drools.getConsequenceDegree());
end

rule "Fan2" 
	when 
		$f : Fan( speed seems[] "slow")
	then
		$f.setSpeed("slow",drools.getConsequenceDegree());
		writer.write("\n\n ********** Set speed to slow ****** \n\n" + drools.getConsequenceDegree());
end

rule "Fan3" 
	when 
		$f : Fan( speed seems[] "stop")
	then
		$f.setSpeed("stop",drools.getConsequenceDegree());
		writer.write("\n\n ********** Set speed to stop ****** \n\n" + drools.getConsequenceDegree());	
end

