package org.drools.examples.chance
 

import org.drools.examples.chance.TestQuantifiers.Message;
import java.io.FileWriter;


global FileWriter writer;

rule "Test Exist"	
	when
		exists(
			m: Message(status == 0)
			
		)
	then
		writer.write("Existential check "+drools.getConsequenceDegree()+"\n");
		System.out.println("Existential check "+drools.getConsequenceDegree()+"\n");	
end


