package org.drools.examples.chance
 

import org.drools.examples.chance.TestDegrees.Message;
import java.io.FileWriter;


global FileWriter writer;

rule "TestOpDegs"	
	when
		(Message(status random[] 0 && status random[] 1)
		or 
		Message(status random[] 2))
		and
		Message(status random[] 3)
									
	then
	
		System.out.println("Degrees test " + drools.getEvaluation().expand());		
		
		writer.write("Degrees test " + drools.getEvaluation().expand());
		
		System.out.println("Final output " + drools.getConsequenceDegree());
end


