package org.drools.examples.chance
 

import org.drools.examples.chance.TestDegrees.Message;
import java.io.FileWriter;


global FileWriter writer;

rule "TestOpDegs"	
	when
		
		(Message( status == 0 && status == 1 )
		or 
		Message(status not random[] 2))
		
		
		not (Message(status random[] 3)
			and
			Message(status random[] 4)
			)
				
		Message(status random[] 5)
		
									
	then
	
		System.out.println("Degrees test " + drools.getEvaluation().expand());		
		
		writer.write("Degrees test " + drools.getEvaluation().expand());
		
		System.out.println("Final output " + drools.getConsequenceDegree());
end


